### ISSUE TITLE
Remove redundant codec and consider adding support for LeoRSFF8

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/rsmt2d#120]
It should be noted that LeoRSFF8 isn't actually GF8 right now because there's no Leopard GF8 in klauspost right now, so that codec should be removed unless Leopard GF8 is implemented (unless we want to still include go-leopard). We haven't made a decision on this yet.

_Originally posted by @musalbas in https://github.com/celestiaorg/rsmt2d/issues/111#issuecomment-1245304954_

this [codec](https://github.com/rahulghangas/rsmt2d/blob/97b11d08a5f073b9f1aa00a98d4946dd83efb5d8/leopard.go#L14) should be removed since it isn't actually using the 8 bit codec. We should also decided if we want to add support for the actual LeoRSFF8 codec.

edit: linked to correct not yet merged codec introduced in #111

**Comment by musalbas** [comment]
The current LeoRSFF8 via go-leopard does use the 8 bit codec as leopard has an FF8 implementation.

However, it is also the case that in LeoRSFF16 when the shards are <256, leopard defaults to using the 8 bit codec. Therefore, LeoRSFF8 can indeed be removed as it doesn't really add anything, _unless_ we want to make it so that LeoRSFF16 always uses the FF16 codec, which there isn't really an advantage to.

**Comment by rootulp** [comment]
The codec mentioned in this issue no longer appears used. This repo has a singular Leopard codec [here](https://github.com/celestiaorg/rsmt2d/blob/91acbb1023e35787ffe5756767a0749c49ab626e/codecs.go#L6-L11) which uses [Leopard GF8](https://github.com/klauspost/reedsolomon#leopard-gf8) when shards <= 256 or [Leopard GF16](https://github.com/klauspost/reedsolomon#leopard-compatible-gf16) when shards > 256. Is this issue still relevant?

What is the difference between LeoRSFF8 and Leopard GF8?

**Comment by musalbas** [comment]
I don't think this issue is relevant anymore because as you say, the Leopard codec uses GF8 when shards <= 256.
