### ISSUE TITLE
`UnmarshalJSON` is limited to the default Tree

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/rsmt2d#275]
## Problem
When we deserialize the EDS [we hardcode the default tree](https://github.com/celestiaorg/rsmt2d/blob/7a8fd8372e84ed73c2e42821b9bb2d0913d18bd1/extendeddatasquare.go#L40C88-L40C88). This is problematic because computed Row and Col roots of the deserialized eds will be utterly different if another custom tree is used.

## Solutions
1. Have a global tree constructor var/registry that `UnmarshalJSON` would use instead
	* Users would then register their trees by name
		* The name would be serialized in the json and deserialization would then get the proper tree by the name
	* This is exactly what happens with the codec.
2.  `UnmarshalEDS` func that accepts the tree.
	* This works in theory, but https://github.com/filecoin-project/go-jsonrpc/blob/17a35772b24f59ceee25cc8d8177a2b255a659ac/client.go#L614 blocks it
	*  If we contribute an option that custom Unmarshall, then we would be able to inject the one for EDS

**Comment by Wondertan** [comment]
The first solution is bulletproof and requires minimum work outside of rsmt2d, as well the same approach is used for Codec, so we should go with it, imo

**Comment by rootulp** [comment]
I don't understand how the original solution was self-describing if celestia-app needs a registry of tree names to tree options. 

I'm in favor of a solution that doesn't need the registry in celestia-app because it was difficult to initialize the registry correctly. IIRC multiple packages in celestia-app were registering the same tree name multiple times.

**Comment by rootulp** [comment]
> Well, self-describing does not imply a lack of registry.

The JSON representation is not self-describing if it depends on a registry from tree name to tree options in order to deserialize. An alternative to writing the tree names in the JSON is to include all of the options needed to describe the tree in the JSON so that no registry is needed. Then the JSON would be self-describing. 

> Do you remember what the difficulty was?
Yes. IIRC multiple packages in celestia-app were registering the same tree name multiple times.
