### ISSUE TITLE
support maintained gf8 RS lib alternative

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/rsmt2d#73]
I think it would be worthwhile to use [this library](https://github.com/klauspost/reedsolomon) instead of [infectious](https://github.com/vivint/infectious) as a default GF8 lib. It is maintained and seems heavily optimized.

**Comment by musalbas** [comment]
It's probably not as optimized as the leopard library though, which using a faster O(log(n)) FFT-based algorithm, whereas most Reed-Solomon libraries use a standard O(n^2) algorithm. We can't mix and match these libraries, because the leopard one uses a "Novel Polynomial Basis", which gives different encoding output.

**Comment by liamsi** [comment]
Sure, I'm absolutely in favour of only having leopard in here if this is the only we want to use. Let's nuke infectious from the main branch entirely then.
